ALTER TABLE commandes_impression
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS somme_totale NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS versement NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS rest NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nombre_produit INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS produits TEXT,
ADD COLUMN IF NOT EXISTS avec_impression BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS frais_impression NUMERIC DEFAULT 0;
